apiVersion: v1
kind: Service
metadata:
  name: workout-service
  namespace: sports-app
spec:
  selector:
    app: workout-service
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
