apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: sports-app
spec:
  selector:
    app: event-service
  ports:
    - name: http
      port: 7000
      targetPort: 7000
  type: ClusterIP
