version: '3.8'

services:
  auth_db:
    image: postgres:15
    container_name: auth_db
    environment:
      POSTGRES_DB: Authentication
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - /mnt/postgres:/var/lib/postgresql/data
    networks:
      - sports-app-net

  minio:
    image: minio/minio:latest
    container_name: minio_sports_project
    ports:
      - "9000:9000" # API Port (Code connects here)
      - "9001:9001" # Console Port (Browser UI)
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password123"
    volumes:
      # This saves your images to a folder named 'minio_data' in the same directory
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - sports-app-net

  sports-zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: sports-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - sports-app-net

  sports-kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: sports-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: sports-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://sports-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - sports-zookeeper
    networks:
      - sports-app-net

  api-gateway:
    image: nginx:1.25-alpine
    container_name: api-gateway
    ports: 
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      auth-service:
        condition: service_started
      team-service:
        condition: service_started
    networks:
      - sports-app-net

  #microservicces
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    environment:
      - PORT=8080
      - CORS_ALLOWED_ORIGINS=http://localhost:5173
      - JWT_SECRET=${JWTSecret}
      - DB_HOST=auth_db 
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_NAME=Authentication
      - KAFKA_BROKER=sports-kafka:9092
    depends_on:
      - auth_db
    networks:
      - sports-app-net

  team-service:
    build:
      context: ./team-service
    container_name: team-service
    environment:
      - PORT=4000
      - CORS_ALLOWED_ORIGINS=http://localhost:5173
      - JWT_SECRET=${JWT_SECRET:-mydogsnameisrufus}
      - DB_HOST=auth_db 
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_NAME=teams
      - KAFKA_BROKER=sports-kafka:9092
      - USER_SERVICE_GRPC_ADDR=user-service:50051
    depends_on:
      - auth_db
    networks:
      - sports-app-net

  event-service:
    build:
      context: ./event-service
    container_name: event-service
    environment:
      - PORT=7000
      - CORS_ALLOWED_ORIGINS=http://localhost:5173
      - JWT_SECRET=${JWT_SECRET:-mydogsnameisrufus}
      - DB_HOST=auth_db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_NAME=teams
      - USER_SERVICE_GRPC_ADDR=user-service:50051
      - TEAM_SERVICE_GRPC_ADDR=team-service:50052
    depends_on:
      - auth_db
    networks:
      - sports-app-net

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    environment:
      - PORT=8081
      - CORS_ALLOWED_ORIGINS=http://localhost:5173
      - JWT_SECRET=${JWT_SECRET:-mydogsnameisrufus}
      - DB_HOST=auth_db 
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_NAME=users
      - KAFKA_BROKER=sports-kafka:9092
      #- USER_SERVICE_GRPC_ADDR=user-service:50051
    depends_on:
      - auth_db
    networks:
      - sports-app-net

  workout-service:
    build:
      context: ./workout-service
    container_name: workout-service
    environment:
      - PORT=3000
      - CORS_ALLOWED_ORIGINS=http://localhost:5173
      - JWT_SECRET=${JWT_SECRET:-mydogsnameisrufus}
      - DB_HOST=auth_db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_NAME=teams
      - USER_SERVICE_GRPC_ADDR=user-service:50051
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password123
      - MINIO_BUCKET=sportspro
      - MINIO_USE_SSL=false
    ports:
      - "8082:3000"
    depends_on:
      - auth_db
      - minio
      - user-service
    networks:
      - sports-app-net


networks:
  sports-app-net:
    driver: bridge