apiVersion: v1
kind: Secret
metadata:
  name: sports-app-secrets
  namespace: sports-app
type: Opaque
stringData:
  # Database URLs (per service)
  AUTH_DB_URL: "postgres://admin:admin123@auth-db:5432/Authentication?sslmode=disable"
  USER_DB_URL: "postgres://admin:admin123@auth-db:5432/users?sslmode=disable"
  TEAM_DB_URL: "postgres://admin:admin123@auth-db:5432/teams?sslmode=disable"
  EVENT_DB_URL: "postgres://admin:admin123@auth-db:5432/teams?sslmode=disable"
  WORKOUT_DB_URL: "postgres://admin:admin123@auth-db:5432/teams?sslmode=disable"

  AUTH_DB_PASSWORD: "admin123"
  USER_DB_PASSWORD: "admin123"
  TEAM_DB_PASSWORD: "admin123"
  EVENT_DB_PASSWORD: "admin123"
  WORKOUT_DB_PASSWORD: "admin123"

  # Auth secrets
  JWT_SECRET_KEY: "mydogsnameisrufus"
  REFRESH_SECRET_KEY: "myotherdogiscalledseedolf"

  # MinIO
  MINIO_ACCESS_KEY: "admin"
  MINIO_SECRET_KEY: "password123"

  # Kafka (fill if using SASL/TLS; else keep empty or remove)
  KAFKA_USERNAME: ""
  KAFKA_PASSWORD: ""