apiVersion: v1
kind: Service
metadata:
  name: sports-gateway-external
  namespace: sports-app
spec:
  type: NodePort
  selector:
    app: frontend  # Point this to your frontend pods
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 # This will be your public port